package com.example.mainactivity.mvvm.profile.model

object ProfileSeed {
    val data: List<ProfileEntity> = listOf(
        ProfileEntity(
            id = 1L,
            name = "Priyanka",
            age = 27,
            height = "5 ft 2 in",
            language = "Tamil",
            religionCommunity = "Hindu - Nair",
            education = "MBBS",
            profession = "Doctor",
            city = "Chennai",
            stateCountry = "Tamil Nadu, India",
            profileIdCode = "M9837832",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 2L,
            name = "Pragati",
            age = 27,
            height = "5 ft 5 in",
            language = "Tamil",
            religionCommunity = "Hindu - Kayastha",
            education = "MBBS",
            profession = "Doctor",
            city = "Chennai",
            stateCountry = "Tamil Nadu",
            profileIdCode = "M1122334",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 3L,
            name = "Ananya",
            age = 26,
            height = "5 ft 4 in",
            language = "English, Hindi",
            religionCommunity = "Hindu - Brahmin",
            education = "B.Tech",
            profession = "Software Engineer",
            city = "Bengaluru",
            stateCountry = "Karnataka, India",
            profileIdCode = "M5566778",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 4L,
            name = "Kavya",
            age = 28,
            height = "5 ft 3 in",
            language = "Telugu",
            religionCommunity = "Hindu - Reddy",
            education = "MBA",
            profession = "Marketing",
            city = "Hyderabad",
            stateCountry = "Telangana, India",
            profileIdCode = "M9988776",
            isVerified = false,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 5L,
            name = "Meera",
            age = 25,
            height = "5 ft 6 in",
            language = "Malayalam",
            religionCommunity = "Hindu - Nair",
            education = "M.Sc",
            profession = "Researcher",
            city = "Kochi",
            stateCountry = "Kerala, India",
            profileIdCode = "M4433221",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 6L,
            name = "Aditi",
            age = 26,
            height = "5 ft 4 in",
            language = "Hindi, English",
            religionCommunity = "Hindu - Agarwal",
            education = "CA",
            profession = "Chartered Accountant",
            city = "Delhi",
            stateCountry = "Delhi NCR, India",
            profileIdCode = "M7711002",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 7L,
            name = "Ishita",
            age = 24,
            height = "5 ft 3 in",
            language = "Bengali, Hindi",
            religionCommunity = "Hindu - Kayastha",
            education = "B.Des",
            profession = "UX Designer",
            city = "Kolkata",
            stateCountry = "West Bengal, India",
            profileIdCode = "M8822003",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 8L,
            name = "Sneha",
            age = 29,
            height = "5 ft 5 in",
            language = "Marathi, Hindi",
            religionCommunity = "Hindu - Maratha",
            education = "M.Com",
            profession = "Banking",
            city = "Pune",
            stateCountry = "Maharashtra, India",
            profileIdCode = "M9933004",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 9L,
            name = "Divya",
            age = 27,
            height = "5 ft 2 in",
            language = "Tamil, English",
            religionCommunity = "Hindu - Iyer",
            education = "LL.B",
            profession = "Lawyer",
            city = "Coimbatore",
            stateCountry = "Tamil Nadu, India",
            profileIdCode = "M1044005",
            isVerified = false,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 10L,
            name = "Riya",
            age = 23,
            height = "5 ft 2 in",
            language = "Hindi, English",
            religionCommunity = "Hindu - Baniya",
            education = "BBA",
            profession = "HR Executive",
            city = "Jaipur",
            stateCountry = "Rajasthan, India",
            profileIdCode = "M2155006",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
    )
}
