package com.example.mainactivity.data.local

object ProfileSeed {
    val data: List<ProfileEntity> = listOf(
        ProfileEntity(
            id = 1L,
            name = "Priyanka",
            age = 27,
            height = "5 ft 2 in",
            language = "Tamil",
            religionCommunity = "Hindu - Nair",
            education = "MBBS",
            profession = "Doctor",
            city = "Chennai",
            stateCountry = "Tamil Nadu, India",
            profileIdCode = "M9837832",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 2L,
            name = "Pragati",
            age = 27,
            height = "5 ft 5 in",
            language = "Tamil",
            religionCommunity = "Hindu - Kayastha",
            education = "MBBS",
            profession = "Doctor",
            city = "Chennai",
            stateCountry = "Tamil Nadu",
            profileIdCode = "M1122334",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 3L,
            name = "Ananya",
            age = 26,
            height = "5 ft 4 in",
            language = "English, Hindi",
            religionCommunity = "Hindu - Brahmin",
            education = "B.Tech",
            profession = "Software Engineer",
            city = "Bengaluru",
            stateCountry = "Karnataka, India",
            profileIdCode = "M5566778",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 4L,
            name = "Kavya",
            age = 28,
            height = "5 ft 3 in",
            language = "Telugu",
            religionCommunity = "Hindu - Reddy",
            education = "MBA",
            profession = "Marketing",
            city = "Hyderabad",
            stateCountry = "Telangana, India",
            profileIdCode = "M9988776",
            isVerified = false,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 5L,
            name = "Meera",
            age = 25,
            height = "5 ft 6 in",
            language = "Malayalam",
            religionCommunity = "Hindu - Nair",
            education = "M.Sc",
            profession = "Researcher",
            city = "Kochi",
            stateCountry = "Kerala, India",
            profileIdCode = "M4433221",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 6L,
            name = "Aditi",
            age = 26,
            height = "5 ft 4 in",
            language = "Hindi, English",
            religionCommunity = "Hindu - Agarwal",
            education = "CA",
            profession = "Chartered Accountant",
            city = "Delhi",
            stateCountry = "Delhi NCR, India",
            profileIdCode = "M7711002",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 7L,
            name = "Ishita",
            age = 24,
            height = "5 ft 3 in",
            language = "Bengali, Hindi",
            religionCommunity = "Hindu - Kayastha",
            education = "B.Des",
            profession = "UX Designer",
            city = "Kolkata",
            stateCountry = "West Bengal, India",
            profileIdCode = "M8822003",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 8L,
            name = "Sneha",
            age = 29,
            height = "5 ft 5 in",
            language = "Marathi, Hindi",
            religionCommunity = "Hindu - Maratha",
            education = "M.Com",
            profession = "Banking",
            city = "Pune",
            stateCountry = "Maharashtra, India",
            profileIdCode = "M9933004",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 9L,
            name = "Divya",
            age = 27,
            height = "5 ft 2 in",
            language = "Tamil, English",
            religionCommunity = "Hindu - Iyer",
            education = "LL.B",
            profession = "Lawyer",
            city = "Coimbatore",
            stateCountry = "Tamil Nadu, India",
            profileIdCode = "M1044005",
            isVerified = false,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 10L,
            name = "Riya",
            age = 23,
            height = "5 ft 2 in",
            language = "Hindi, English",
            religionCommunity = "Hindu - Baniya",
            education = "BBA",
            profession = "HR Executive",
            city = "Jaipur",
            stateCountry = "Rajasthan, India",
            profileIdCode = "M2155006",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 11L,
            name = "Nisha",
            age = 28,
            height = "5 ft 3 in",
            language = "Punjabi, Hindi",
            religionCommunity = "Sikh",
            education = "M.Pharm",
            profession = "Pharmacist",
            city = "Chandigarh",
            stateCountry = "Punjab, India",
            profileIdCode = "M3266007",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 12L,
            name = "Pooja",
            age = 26,
            height = "5 ft 4 in",
            language = "English, Kannada",
            religionCommunity = "Hindu - Bunt",
            education = "B.Arch",
            profession = "Architect",
            city = "Mysuru",
            stateCountry = "Karnataka, India",
            profileIdCode = "M4377008",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 13L,
            name = "Shruti",
            age = 30,
            height = "5 ft 5 in",
            language = "Hindi, English",
            religionCommunity = "Hindu - Rajput",
            education = "M.Tech",
            profession = "Data Scientist",
            city = "Gurugram",
            stateCountry = "Haryana, India",
            profileIdCode = "M5488009",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 14L,
            name = "Tanvi",
            age = 25,
            height = "5 ft 3 in",
            language = "Gujarati, Hindi",
            religionCommunity = "Hindu - Brahmin",
            education = "BDS",
            profession = "Dentist",
            city = "Ahmedabad",
            stateCountry = "Gujarat, India",
            profileIdCode = "M6599010",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 15L,
            name = "Lakshmi",
            age = 27,
            height = "5 ft 2 in",
            language = "Tamil, English",
            religionCommunity = "Hindu - Nadar",
            education = "B.Ed",
            profession = "Teacher",
            city = "Madurai",
            stateCountry = "Tamil Nadu, India",
            profileIdCode = "M7600111",
            isVerified = false,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 16L,
            name = "Neha",
            age = 29,
            height = "5 ft 4 in",
            language = "Hindi, English",
            religionCommunity = "Hindu - Khatri",
            education = "PGDM",
            profession = "Consultant",
            city = "Noida",
            stateCountry = "Uttar Pradesh, India",
            profileIdCode = "M8711222",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 17L,
            name = "Swati",
            age = 26,
            height = "5 ft 4 in",
            language = "Odia, Hindi",
            religionCommunity = "Hindu - Karan",
            education = "MBBS",
            profession = "Doctor",
            city = "Bhubaneswar",
            stateCountry = "Odisha, India",
            profileIdCode = "M9822333",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 18L,
            name = "Aarohi",
            age = 24,
            height = "5 ft 1 in",
            language = "Assamese, English",
            religionCommunity = "Hindu - Kalita",
            education = "B.Sc Nursing",
            profession = "Nurse",
            city = "Guwahati",
            stateCountry = "Assam, India",
            profileIdCode = "M1933444",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 19L,
            name = "Vidya",
            age = 31,
            height = "5 ft 2 in",
            language = "Tamil, English",
            religionCommunity = "Hindu - Vanniyar",
            education = "Ph.D",
            profession = "Professor",
            city = "Tiruchirappalli",
            stateCountry = "Tamil Nadu, India",
            profileIdCode = "M3044555",
            isVerified = true,
            isPremiumNri = true,
            photoCount = 5,
        ),
        ProfileEntity(
            id = 20L,
            name = "Zara",
            age = 28,
            height = "5 ft 5 in",
            language = "Urdu, Hindi",
            religionCommunity = "Muslim",
            education = "B.Com",
            profession = "Entrepreneur",
            city = "Lucknow",
            stateCountry = "Uttar Pradesh, India",
            profileIdCode = "M4155666",
            isVerified = true,
            isPremiumNri = false,
            photoCount = 5,
        ),
    )
}
